spring:
  application:
    name: actuator

server:
  port: 8080

management:
  server:
    port: 4000
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /details
  endpoint:
    health:
      show-details: always
